### ISSUE TITLE
ERROR IN RECEIVE MIDDLEWARE:  TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by mhjb** [mrbot-ai/botkit-middleware-fbuser#1]
Any idea?

![image](https://cloud.githubusercontent.com/assets/1380991/25737551/99bd7768-31cc-11e7-9198-7744f021b0e3.png)

**Comment by znat** [comment]
The module doesn't find the users collection in Botkit storage. My guess is your storage is not initialized properly. If you need more help, please re-open and tell me what storage option you're using.
