### ISSUE TITLE
OAuthException

### ISSUE THREAD

**Issue by mhjb** [mrbot-ai/botkit-middleware-fbuser#3]
Hi there

Today I'm seeing the below error. The FB page access token is working for the botkit controller. (Note if you like the misspelled 'occured' too:)

```
An error occured in the receive middleware:  
{ message: '(#2) Service temporarily unavailable',
  type: 'OAuthException',
  is_transient: true,
  code: 2,
  fbtrace_id: 'DcPlLK/08Sc' }
```

Thanks for your help.
Matthew

**Comment by znat** [comment]
Probably a page token issue

**Comment by mhjb** [comment]
Today it's working, with no change to the code. The page token continued to work yesterday for the main botkit controller. Would be interesting to know what happened, as I'd like to use this in production eventually.
